config/routes.rb
Outfly2::Application.routes.draw do

  devise_for :users do
      resources :entries
  end

  root :to => 'static_pages#home'

  get "about" => "static_pages#about"

  get "contact" => "static_pages#contact"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	
  # Include default devise modules. Others available are:has-
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
	attr_accessible :id, :email, :password, :password_confirmation, :remember_me
	
	has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @user = current_user
    @entries = @user.entries.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @user = current_user
    @entry = @user.entries.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/entries/_form.html.erb
<%= simple_form_for(@entry) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :description %>
    <%= f.input :airtemp, :label => "Air Temp" %>
    <%= f.input :watertemp, :label => "Water Temp" %>
    <%= f.input :conditions, :collection => ["Sunny", "Partly Sunny", "Partly Cloudy", "Cloudy", "Rain", "Snow"] %>
    <%= f.input :speciessought, :label => "Species Sought" %>
    <%= f.input :speciescaught, :label => "Species Caught" %>
    <%= f.input :flypattern, :label => "Fly Pattern" %>
    <%= f.input :pressure, :label => "Fishing Pressure", :collection => ["Light", "Medium", "Heavy"] %>
    <%= f.input :rating, :collection => 1..5 %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>My Fly-fishing Journal</h1>

<table width="960">
<tr>
<th>Date</th>
<th>City</th>
<th>State</th>
<th>Air </br>temp</th>
<th>Water </br>temp</th>
<th>Conditions</th>
<th>Species </br>caught</th>
<th>Rating</th>
<th></th>
<th></th>
<th></th>
</tr>

<% @entries.each do |entry| %>
<tr>
<td width="12%"><center><%= entry.date %></center></td>
<td width="10%"><center><%= entry.city %></center></td>
<td width="8%"><center><%= entry.state %></center></td>
<td><center><%= entry.airtemp %></center></td>
<td><center><%= entry.watertemp %></center></td>
<td><center><%= entry.conditions %></center></td>
<td><center><%= entry.speciescaught %></center></td>
<td><center><%= entry.rating %></center></td>
<td><%= link_to 'Show', entry, class: "btn btn-mini" %></td>
<td><%= link_to 'Edit', edit_entry_path(entry), class: "btn btn-mini" %></td>
<td><%= link_to 'Destroy', entry, class: "btn btn-mini btn-danger", confirm: 'Are you sure?', method: :delete %></td>
</tr>
<% end %>

</table>

<br />

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1 style="padding-bottom:20px;">New Journal Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @entry.date %>
</p>

<p>
  <b>City:</b>
  <%= @entry.city %>
</p>

<p>
  <b>State:</b>
  <%= @entry.state %>
</p>

<p>
  <b>Description:</b>
  <%= @entry.description %>
</p>

<p>
  <b>Air Temp:</b>
  <%= @entry.airtemp %>
</p>

<p>
  <b>Water Temp:</b>
  <%= @entry.watertemp %>
</p>

<p>
  <b>Conditions:</b>
  <%= @entry.conditions %>
</p>

<p>
  <b>Species Sought:</b>
  <%= @entry.speciessought %>
</p>

<p>
  <b>Species Caught:</b>
  <%= @entry.speciescaught %>
</p>

<p>
  <b>Fly Pattern:</b>
  <%= @entry.flypattern %>
</p>

<p>
  <b>Pressure:</b>
  <%= @entry.pressure %>
</p>

<p>
  <b>Rating:</b>
  <%= @entry.rating %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoutFly the Social Fly-Fishing App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <style type="text/css">
      body {
        padding: 20px;
      }
  </style> 
    
</head>

<body>



  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <div class="container-fluid">
        <!-- <a class="brand" href="#"><img src="/assets/tiny_logo_test1.png" /></a> -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <%= link_to "ShoutFly", root_path, class: "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <li> <%= link_to "Home", root_path, class: "active" %> </li>
            <li> <%= link_to "About", about_path %> </li>
            <li> <%= link_to "Contact", contact_path %></li>
          </ul>
          <ul class="nav pull-right">
            <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
            <li class="divider-vertical"></li>

            <% if user_signed_in? %>
            <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
            <% end %>
          </ul> <!-- pull right -->
        </div><!-- /.nav-collapse -->
      </div>
    </div><!-- /navbar-inner -->
  </div>

  <div class="container">

    <% flash.each do |key, value| %>
    <%= contePnt_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
   
    <%= yield %>

  </div><!-- container -->

<footer>
  <div class="container">
    <div class="row">

      <div class="span4">
       
       <h4>ShoutFly</h4>

          <p>
            <i class="icon-map-marker icon-white"></i> 30 Park Avenue
          </p>
          <p> 
            <i class="icon-map-marker icon-white"></i> New York, NY 00123, USA
          </p>  
          <p> 
            <i class="icon-bell icon-white"></i> Phone: (123) 456-7890
          </p>
          <p> 
            <i class="icon-inbox icon-white"></i> Fax: +08 (123) 456-7890
          </p>
          <p>
            <i class="icon-envelope icon-white"></i> Email: contact@companyname.com
          </p>
          <p>
            <i class="icon-home icon-white"></i> Web: companyname.com
          </p>
        
      </div>
      <div class="span4">
        <h4>Latest Tweets</h4>
          
          <ul id="twitter">
            
          </ul>

          <div class="clear"></div>
      </div>
      <div class="span4">
        
      </div>
      
    </div><!-- end row -->
  </div><!-- end container -->  

</footer>

</body>

</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
 <% if user_signed_in? %>

<div class="row">

 <h2 style="padding-bottom:40px;"> Welcome fly-fisher! </h2>

  <div class="span6">
    <center><img src="/assets/journal.jpg" class="img-rounded" alt="" style="padding-bottom:20px;">
      <p>
      <%= link_to "New Journal Entry", new_entry_path, class: "btn" %>
  	  </p>
      <p></p>
    </center>
  </div><!-- span -->

  <!-- <div class="span4">
    <center><img src="/assets/photo_flyfishing.jpg" class="img-rounded" alt="" style="padding-bottom:20px;">
      <p>
  		<button class="btn" type="button">Add a Photo</button>
  	  </p>
      <p></p>
    </center>
  </div> -->

  <div class="span6">
    <center><img src="/assets/read_journal.jpg" class="img-rounded" alt="" style="padding-bottom:20px;">
      <p>
  		<%= link_to "Browse/Edit Journal", entries_path, class: "btn" %>
  	  </p>
      <p></p>
    </center>
  </div><!-- span -->

</div><!-- row -->

 <% else %>

<div class="row">
<div class="span12">
<div id="myCarousel" class="carousel slide">
  <!-- Carousel items -->
  <div class="carousel-inner">

    <div class="item active">
      <img src="/assets/flyfishing2.jpg" alt="">
        <div>
          <h4>ShoutFly is...</h4>
          <p>...your personal and social fly-fishing journal and virtual guide.  Take ShoutFly with you or record your trips at home.  Always have access to your entries - and advice from the ShoutFly community.</p>
        </div>
    </div>
                  
    <div class="item">
      <img src="/assets/flyfishing1.jpg" alt="">
        <div>
          <h4>Be a better fly-fisher...</h4>
          <p>...record the locations, conditions, flies used, successes and failures, save photos and share (or not) as you please! </p>
        </div>
    </div>
                  
    <div class="item">
      <img src="/assets/flyfishing3.jpg" alt="">
        <div>
          <h4>On your next outing...</h4>
          <p>...refer to your prior journal entries, search for location or conditions, or search the OutFly community for additional advice and suggestions...winning!</p>
        </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div> <!-- carousel -->
</div> <!-- span -->
</div> <!-- row -->

<hr>

<div class="row" style="padding-bottom:26px">
<center><h3>Fly-fishing love from our community...</h3></center>
</div><!-- row -->

<div class="row">

  <div class="span4">
    <center><img src="/assets/john_redfish.jpg" class="img-circle" alt="">
      <h4>John I.<br>Naples, FL</h4>
      <p>"ShoutFly helps me remember the most effective fly to fish under variable conditions, in locations far and wide - and I can share my fishing pics with family and friends on Facebook and Twitter!"</p>
    </center>
  </div><!-- span -->

  <div class="span4">
    <center><img src="/assets/bill_trout.jpg" class="img-circle" alt="">
      <h4>Bill D.<br>Sparta, NJ</h4>
      <p>"As a new fly-fisherman I really needed an app to help me record what I'd learned, and search for advice & new spots to fish.  ShoutFly does all of that and more - an invaluable tool for this sport!"</p>
    </center>
  </div><!-- span -->

  <div class="span4">
    <center><img src="/assets/sean_trout.jpg" class="img-circle" alt="">
      <h4>Sean F.<br>Suffern, NY</h4>
      <p>"The first time my Dad took me to Pulaski, I caught this beautiful brown trout - I'll never forget it!  Recorded this catch in my ShoutFly virtual creel and shared on Facebook!"</p>
    </center>
  </div><!-- span -->

</div><!-- row -->


<hr>

<% end %>